POST http://localhost:3003/api/blogs
Content-Type: application/json; charset=utf-8

{
    "title": "Testi blogi numero 4",
    "author": "Miika Valkonen",
    "url": "Testi urli 4",
    "likes": 55000
}